### ISSUE TITLE
Bug: Expo Module Function does not work AT ALL! https://docs.expo.dev/modules/module-api/#function

### ISSUE THREAD

**Issue by williscool** [williscool/CalendarNotification#13]
this is a bug somewhere in the expo implementation that I want to report to them

I plan to leave the MyModule library and do my own native module in a seperate one as a refence.

**Comment by williscool** [comment]
fairly certain its this issue

```
2023-10-12 02:27:15.442  9348-10511 unknown:ReactNative     com.github.quarck.calnotify          E  Exception in native call
                                                                                                    java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: HMRClient.setup()
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2023-10-12 02:27:42.321  9348-9419  OpenGLRenderer          com.github.quarck.calnotify          E  Unable to match the desired swap behavior.

```

**Comment by williscool** [comment]
will report here whenever I have time

https://github.com/expo/expo/issues/new?assignees=&labels=needs+validation&projects=&template=bug_report.yml

**Comment by williscool** [comment]
SOOOOOOOOOOOOOOOO.

It turns out this is a KNOWN but poorly documented issue. Syncronous functions DO NOT WORK IN THE CHROME DEBUGGER!!!!!!

but they do work when run in hermes (the runtime react native uses internally)

https://reactnative.dev/docs/native-modules-android?android-language=kotlin#synchronous-methods

https://reactnative.dev/blog/2021/10/26/toward-hermes-being-the-default#pioneering-at-vertical-integrations

**Comment by williscool** [comment]
If you want to debug them with chrome you gotta make this setup work

https://reactnative.dev/docs/hermes?package-manager=yarn#debugging-js-on-hermes-using-google-chromes-devtools

or use flipper

https://shopify.github.io/react-native-skia/docs/getting-started/installation/#debugging

**Comment by williscool** [comment]
As documentes heavily in. #12 

This doesn't work at all in the Chrome debugger even though it does work you just can't debug it at all.

Last thing I want to do is override this function with a warning that says that it is heavily suggested that you don't use this and just return the super.

Will prefer async functions for everything unless there is absolutely no other way to implement a feature that I want
